
class PictureParameters:
    def __init__(self):
        self.pictureName = "New Picture"
        self.createSymbol = "True"
        self.symbolFolder = ""
        self.withImage = "False"
        self.imageWidth = "8\""
        self.imageHeight = "10\""
        self.imagePosition = "0.3\""
        self.imageTexture = ""
        self.withFrame = "True"
        self.frameWidth = "12\""
        self.frameHeight = "14\""
        self.frameThickness = "1\""
        self.frameDepth = "1\""
        self.frameClass = "None"
        self.frameTextureScale = "1"
        self.frameTextureRotation = "0"
        self.withMatboard = "True"
        self.matboardPosition = "0.25\""
        self.matboardClass = "None"
        self.matboardTextureScale = "1"
        self.matboardTextureRotat = "0"
        self.withGlass = "False"
        self.glassPosition = "0.75\""
        self.glassClass = "None"


class PictureRecord:
    def __init__(self):
        self.artworkTitle = ""
        self.authorName = ""
        self.artworkCreationDate = ""
        self.artworkMedia = ""
        self.type = ""
        self.roomLocation = ""
        self.artworkSource = ""
        self.registrationNumber = ""
        self.authorBirthCountry = ""
        self.authorBirthDate = ""
        self.authorDeathDate = ""
        self.designNotes = ""
        self.exhibitionMedia = ""
